deployment:
  viaShell:
    enabled: false
    commands:
      - enabled: false
        cmd: "qixd --name 'sense-media-box' --app 'sense-media-box.qvf' --documentMount ${PWD}/example --extensionsMount ${PWD}/build/dev --clientMount ~/sense-client/2017-06"
      - enabled: false
        cmd: "docker-compose up --build"
  toSsh:                            # Upload via SSH
    enabled: false
    host: "192.168.56.13"
    port: 22
    username: "stefanwalther"
    password: "Test1234"
    dest: "/cygdrive/c/Users/stefanwalther/Documents/Qlik/Sense/Extensions/sense-media-box"
